### ISSUE TITLE
move repo to symfony-cmf

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/phpcrbrowser#6]
it would be best to update this repo to reflect the fork in symfony-cmf organisation, then delete the fork and move this repo over to symfony-cmf  (chregu can do this in admin in the "Danger Zone" because your are an admin of symfony-cmf)

there was quite a bit of confusion over the fork that we declared being the primary repository...

**Comment by chregu** [comment]
I merged now the symfony-cmf master back to my branch. I guess we should now delete the symfony-cms repo and move mine to symfony-cms for having the "correct" history

SOlution 2) Just add an OBSOLETE file to mine and point to symfony-cmf as the master? That would be far easier and people wouldn't end up with an empty/non-existing remote repo ;)

**Comment by dbu** [comment]
thanks a lot chregu!
